# Generated by Django 5.2.17 on 2026-09-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_usernames_without_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="duel_rating",
            field=models.IntegerField(default=1200),
        ),
    ]
