# Generated by Django 5.2.17 on 2026-09-27 07:21

import secrets

from django.db import migrations, models

_ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"


def fill_join_codes(apps, schema_editor):
    Group = apps.get_model("accounts", "Group")
    used = set()
    for g in Group.objects.filter(join_code__isnull=True):
        code = "".join(secrets.choice(_ALPHABET) for _ in range(6))
        while code in used or Group.objects.filter(join_code=code).exists():
            code = "".join(secrets.choice(_ALPHABET) for _ in range(6))
        used.add(code)
        g.join_code = code
        g.save(update_fields=["join_code"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_duel_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="join_code",
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="teacher_requested",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(fill_join_codes, migrations.RunPython.noop),
    ]
