# Generated by Django 5.2.17 on 2026-09-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_teacher_request_join_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="seen_tier",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
