# Generated by Django 5.2.17 on 2026-09-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_seen_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="honor_pledged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
