# Generated by Django 5.2.17 on 2026-10-04 04:28

from django.db import migrations, models


def to_new_scale(apps, schema_editor):
    """Shown ratings now start at 0 (apps.contests.rating): users who never finished a rated
    contest drop their old 1200 default. Everyone else is rebuilt by `recalc_rating --replay`,
    which needs the app's standings code, so it runs after deploy, not here. Tier names changed
    too: forget the last seen tier so the first visit records the new one instead of
    congratulating."""
    User = apps.get_model("accounts", "User")
    Participation = apps.get_model("contests", "Participation")
    rated = Participation.objects.filter(rating_after__isnull=False).values("user_id")
    User.objects.exclude(pk__in=rated).update(rating=0)
    User.objects.update(seen_tier="")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_official_rating'),
        ('contests', '0009_official_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(to_new_scale, migrations.RunPython.noop),
    ]
