# Generated by Django 5.2.17 on 2026-10-08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0012_english_tier_names")]

    operations = [
        migrations.CreateModel(
            name="TelegramLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chat_id", models.CharField(max_length=32, unique=True)),
                ("username", models.CharField(blank=True, max_length=64)),
                ("connected_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                ("notify_submissions", models.BooleanField(default=True)),
                ("notify_daily_problem", models.BooleanField(default=True)),
                ("notify_contests", models.BooleanField(default=True)),
                ("last_error", models.CharField(blank=True, max_length=200)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                               related_name="telegram_link", to="accounts.user")),
            ],
        ),
        migrations.CreateModel(
            name="TelegramLinkToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name="telegram_link_tokens", to="accounts.user")),
            ],
        ),
        migrations.CreateModel(
            name="TelegramOutbox",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_key", models.CharField(max_length=160)),
                ("preference", models.CharField(max_length=32)),
                ("text", models.TextField()),
                ("status", models.CharField(choices=[("pending", "Kutilmoqda"), ("sending", "Yuborilmoqda"),
                                                      ("sent", "Yuborildi"), ("failed", "Xato")],
                                             default="pending", max_length=10)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("available_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=300)),
                ("link", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name="outbox", to="accounts.telegramlink")),
            ],
        ),
        migrations.AddConstraint(
            model_name="telegramoutbox",
            constraint=models.UniqueConstraint(fields=("link", "event_key"), name="telegram_outbox_event_once"),
        ),
        migrations.AddIndex(
            model_name="telegramoutbox",
            index=models.Index(fields=["status", "available_at"], name="accounts_tg_status_avail_idx"),
        ),
    ]
