# Generated by Django 5.2.17 on 2026-09-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='mem_kb',
            field=models.IntegerField(default=0),
        ),
    ]
