# Generated by Django 5.2.17 on 2026-09-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_testresult_mem_kb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('AC', 'Ac'), ('WA', 'Wa'), ('TLE', 'Tle'), ('MLE', 'Mle'), ('OLE', 'Ole'), ('RE', 'Re'), ('CE', 'Ce')], default='PENDING', max_length=8),
        ),
    ]
