# Generated by Django 5.2.17 on 2026-09-26 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_submission_verdict_ole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproblemsolved',
            name='first_ac_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.submission'),
        ),
    ]
