# Generated by Django 5.2.17 on 2026-09-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0005_userproblemsolved_cascade"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="device",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="submission",
            name="ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="tracker_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
