# Generated by Django 5.2.17 on 2026-09-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0006_submission_telemetry"),
    ]

    operations = [
        migrations.AddField(
            model_name="userproblemsolved",
            name="hint_pct",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
