# Generated by Django 5.2.17 on 2026-09-26 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contests", "0008_virtualparticipation"),
        ("submissions", "0007_userproblemsolved_hint_pct"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="virtual",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to="contests.virtualparticipation",
            ),
        ),
    ]
