# Generated by Django 5.2.17 on 2026-09-27 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def to_own_clocks(apps, schema_editor):
    """Duels used to run both players on one clock from the accept: a running one keeps
    that as both clocks; a challenge still waiting has no problem or clock of its own
    to hand over, so it lapses."""
    Duel = apps.get_model("classroom", "Duel")
    Duel.objects.filter(status="active").update(opponent_started_at=models.F("started_at"),
                                                opponent_ends_at=models.F("ends_at"))
    Duel.objects.filter(status="pending", started_at__isnull=True).update(status="expired")


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_duel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='opponent_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duel',
            name='opponent_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duel',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='duel',
            name='status',
            field=models.CharField(choices=[('pending', 'Raqib kutilmoqda'), ('active', 'Davom etmoqda'), ('finished', 'Tugagan'), ('declined', 'Rad etilgan'), ('expired', 'Muddati o‘tgan')], default='pending', max_length=10),
        ),
        migrations.RunPython(to_own_clocks, migrations.RunPython.noop),
    ]
