# Generated by Django 5.2.17 on 2026-09-17 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        ('submissions', '0002_submission_contest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('reviewed', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('submission_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='submissions.submission')),
                ('submission_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='submissions.submission')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='FocusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('blur', 'Blur'), ('focus', 'Focus'), ('paste', 'Paste'), ('copy', 'Copy')], max_length=10)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_events', to='contests.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['contest', 'user'], name='integrity_f_contest_fbcd93_idx')],
            },
        ),
    ]
