# Generated by Django 5.2.17 on 2026-09-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusevent',
            name='kind',
            field=models.CharField(choices=[('blur', 'Blur'), ('focus', 'Focus'), ('paste', 'Paste'), ('copy', 'Copy'), ('fast', 'Fast')], max_length=10),
        ),
    ]
