# Generated by Django 5.2.17 on 2026-09-23 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_drop_icpc_type'),
        ('integrity', '0002_focusevent_fast_kind'),
        ('problems', '0009_problem_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='focusevent',
            name='away_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='focusevent',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='problems.problem'),
        ),
        migrations.AlterField(
            model_name='focusevent',
            name='kind',
            field=models.CharField(choices=[('blur', 'Blur'), ('focus', 'Focus'), ('paste', 'Paste'), ('copy', 'Copy'), ('fast', 'Fast'), ('view', 'View')], max_length=10),
        ),
        migrations.CreateModel(
            name='CodeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contests.contest')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='problems.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['contest', 'user', 'problem', 'at'], name='integrity_c_contest_c2f00f_idx')],
            },
        ),
    ]
