# Generated by Django 5.2.17 on 2026-09-26 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contests", "0007_participation_last_seen_at"),
        ("integrity", "0004_deviceseen"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("disqualify", "Diskvalifikatsiya"),
                            ("requalify", "Diskvalifikatsiya bekor"),
                            ("rejudge", "Qayta tekshiruv"),
                            ("publish", "Masalalar ochildi"),
                            ("rating_apply", "Reyting hisoblandi"),
                            ("rating_recompute", "Reyting qayta hisoblandi"),
                            ("flag_review", "O‘xshashlik ko‘rildi"),
                            ("problem_delete", "Masala o‘chirildi"),
                            ("contest_delete", "Musobaqa o‘chirildi"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contests.contest",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-at", "-id"],
            },
        ),
    ]
