# Generated by Django 5.2.17 on 2026-10-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrity', '0007_practice_snapshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditentry',
            name='action',
            field=models.CharField(choices=[('disqualify', 'Diskvalifikatsiya'), ('requalify', 'Diskvalifikatsiya bekor'), ('rejudge', 'Qayta tekshiruv'), ('publish', 'Masalalar ochildi'), ('rating_apply', 'Reyting hisoblandi'), ('rating_recompute', 'Reyting qayta hisoblandi'), ('flag_review', 'O‘xshashlik ko‘rildi'), ('problem_delete', 'Masala o‘chirildi'), ('contest_delete', 'Musobaqa o‘chirildi'), ('user_delete', 'Foydalanuvchi o‘chirildi')], max_length=20),
        ),
    ]
