# Generated by Django 5.2.17 on 2026-10-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrity', '0010_audit_void'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarityflag',
            name='deep',
            field=models.BooleanField(default=False),
        ),
    ]
