# Generated by Django 5.2.17 on 2026-09-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_clarification'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='disqualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participation',
            name='disqualified_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
