# Generated by Django 5.2.17 on 2026-09-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_participation_disqualified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='type',
            field=models.CharField(choices=[('icpc', 'ICPC'), ('score', 'Ball')], default='icpc', max_length=10),
        ),
    ]
