# Generated by Django 5.2.17 on 2026-09-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_contest_type_labels'),
    ]

    operations = [
        # Existing ICPC contests become score contests; their per-problem points
        # decide the order now (penalty is still the tie-break).
        migrations.RunSQL("UPDATE contests_contest SET type = 'score' WHERE type = 'icpc'",
                          migrations.RunSQL.noop),
        migrations.AlterField(
            model_name='contest',
            name='type',
            field=models.CharField(choices=[('score', 'Ball')], default='score', max_length=10),
        ),
    ]
