# Generated by Django 5.2.17 on 2026-09-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contests", "0006_contest_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="participation",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
