# Generated by Django 5.2.17 on 2026-10-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_virtualparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='official_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='review_top_n',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='participation',
            name='official_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='official_before',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
