# Generated by Django 5.2.17 on 2026-10-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_official_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='division',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ochiq (hamma uchun)'), (1, 'Div. 1 (reyting 1900 va yuqori)'), (2, 'Div. 2 (reyting 1900 dan past)'), (3, 'Div. 3 (reyting 1600 dan past)'), (4, 'Div. 4 (reyting 1400 dan past)')], default=0),
        ),
    ]
