# Generated by Django 5.2.17 on 2026-10-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_contest_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='type',
            field=models.CharField(choices=[('score', 'Ball: to‘liq ball, tenglikda jarima'), ('cf', 'Codeforces: ball vaqt bilan kamayadi'), ('icpc', 'ICPC: yechilganlar soni va jarima')], default='score', max_length=10),
        ),
    ]
