# Generated by Django 5.2.17 on 2026-10-05 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0012_contest_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoidedProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('contest_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voids', to='contests.contestproblem')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voids', to='contests.participation')),
            ],
            options={
                'unique_together': {('participation', 'contest_problem')},
            },
        ),
    ]
