# Generated by Django 5.2.17 on 2026-10-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0014_contest_similarity_checked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='badge',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
