# Generated by Django 5.2.17 on 2026-10-01 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0015_tag_about_md'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('intro_md', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('description_md', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='beginner', max_length=10)),
                ('icon', models.CharField(choices=[('book-open', 'book-open'), ('footprints', 'footprints'), ('brackets', 'brackets'), ('route', 'route'), ('database', 'database'), ('graduation-cap', 'graduation-cap'), ('binary', 'binary'), ('network', 'network'), ('sigma', 'sigma'), ('code', 'code'), ('puzzle', 'puzzle'), ('rocket', 'rocket'), ('target', 'target'), ('trophy', 'trophy'), ('brain', 'brain'), ('layers', 'layers')], default='book-open', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('in_quest', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='problems.problem')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='learn.plansection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProblemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('is_public', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-id'],
            },
        ),
        migrations.AddField(
            model_name='plansection',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='learn.studyplan'),
        ),
        migrations.CreateModel(
            name='ProblemListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='learn.problemlist')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='problems.problem')),
            ],
            options={
                'ordering': ['-added', '-id'],
                'unique_together': {('list', 'problem')},
            },
        ),
    ]
