# Generated by Django 5.2.17 on 2026-10-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
        ('problems', '0015_tag_about_md'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='stage',
            field=models.CharField(choices=[('basics', 'Asoslar'), ('python', 'Python vositalari'), ('algorithms', 'Algoritmlar'), ('techniques', 'Texnikalar'), ('structures', 'Ma’lumot tuzilmalari'), ('math', 'Matematika'), ('dp', 'Dinamik dasturlash'), ('graphs', 'Graflar'), ('advanced', 'Ilg‘or'), ('sql', 'SQL')], default='basics', max_length=12),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='courses', to='problems.tag'),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='theory_md',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='icon',
            field=models.CharField(choices=[('book-open', 'book-open'), ('footprints', 'footprints'), ('brackets', 'brackets'), ('route', 'route'), ('database', 'database'), ('graduation-cap', 'graduation-cap'), ('binary', 'binary'), ('network', 'network'), ('sigma', 'sigma'), ('code', 'code'), ('puzzle', 'puzzle'), ('rocket', 'rocket'), ('target', 'target'), ('trophy', 'trophy'), ('brain', 'brain'), ('layers', 'layers'), ('terminal', 'terminal'), ('calculator', 'calculator'), ('git-branch', 'git-branch'), ('repeat', 'repeat'), ('rotate-cw', 'rotate-cw'), ('repeat-2', 'repeat-2'), ('hash', 'hash'), ('type', 'type'), ('grid-3x3', 'grid-3x3'), ('book-key', 'book-key'), ('square-function', 'square-function'), ('gauge', 'gauge'), ('arrow-down-up', 'arrow-down-up'), ('search', 'search'), ('arrow-left-right', 'arrow-left-right'), ('move-horizontal', 'move-horizontal'), ('coins', 'coins'), ('undo-2', 'undo-2'), ('pyramid', 'pyramid'), ('percent', 'percent'), ('dices', 'dices'), ('git-merge', 'git-merge'), ('list-tree', 'list-tree'), ('ruler', 'ruler'), ('text-search', 'text-search'), ('shapes', 'shapes'), ('arrow-down-a-z', 'arrow-down-a-z'), ('group', 'group'), ('combine', 'combine'), ('table', 'table')], default='book-open', max_length=40),
        ),
    ]
