# Generated by Django 5.2.17 on 2026-09-20 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={},
        ),
        migrations.AddField(
            model_name='problem',
            name='kind',
            field=models.CharField(choices=[('code', 'Code'), ('sql', 'Sql')], default='code', max_length=10),
        ),
        migrations.CreateModel(
            name='SQLDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_sql', models.TextField(help_text='CREATE TABLE statements, run once per submission.')),
                ('seed_sql', models.TextField(help_text='INSERT statements, run once per submission.')),
                ('expected_result', models.TextField(help_text="Correct query's result, one row per line, tab-separated values, no header. Row order doesn't matter (compared as a sorted set); column order does.")),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sql_dataset', to='problems.problem')),
            ],
        ),
    ]
