# Generated by Django 5.2.17 on 2026-09-20 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_alter_testcase_options_problem_kind_sqldataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='ml_mb',
            field=models.IntegerField(default=256, validators=[django.core.validators.MinValueValidator(6)]),
        ),
    ]
