# Generated by Django 5.2.17 on 2026-09-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_alter_problem_ml_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='input_md',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_md',
            field=models.TextField(blank=True),
        ),
    ]
