# Generated by Django 5.2.17 on 2026-09-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_problem_input_output_md'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='kind',
            field=models.CharField(choices=[('code', 'Dasturlash'), ('sql', 'SQL')], default='code', max_length=10),
        ),
    ]
