# Generated by Django 5.2.17 on 2026-09-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_problem_kind_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('easy', 'Easy'), ('medium', 'Medium'), ('advanced', 'Advanced'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
