# Generated by Django 5.2.17 on 2026-09-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_problem_difficulty_5_levels'),
    ]

    operations = [
        migrations.RunSQL("UPDATE problems_problem SET difficulty = 'hard' WHERE difficulty = 'advanced'",
                          migrations.RunSQL.noop),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
