# Generated by Django 5.2.17 on 2026-09-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_problem_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['order', 'id']},
        ),
    ]
