# Generated by Django 5.2.17 on 2026-09-28 17:44

import django.core.validators
from django.db import migrations, models


def sql_topic_is_sql(apps, schema_editor):
    apps.get_model("problems", "Tag").objects.filter(name="sql").update(kind="sql")


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0013_standard_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqldataset',
            name='check_expected_result',
            field=models.TextField(blank=True, help_text="Correct query's result on the check data."),
        ),
        migrations.AddField(
            model_name='sqldataset',
            name='check_seed_sql',
            field=models.TextField(blank=True, help_text='INSERT statements of the hidden check data.'),
        ),
        migrations.AddField(
            model_name='sqldataset',
            name='ordered',
            field=models.BooleanField(default=False, help_text='The task asks for an ORDER BY: rows must come in order.'),
        ),
        migrations.AddField(
            model_name='tag',
            name='kind',
            field=models.CharField(choices=[('code', 'Dasturlash'), ('sql', 'SQL')], default='code', max_length=10),
        ),
        migrations.AlterField(
            model_name='problem',
            name='ml_mb',
            field=models.IntegerField(default=64, validators=[django.core.validators.MinValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='sqldataset',
            name='expected_result',
            field=models.TextField(help_text="Correct query's result on the sample data, one row per line, tab-separated values, no header. Column order always matters; row order only when `ordered`."),
        ),
        migrations.AlterField(
            model_name='sqldataset',
            name='seed_sql',
            field=models.TextField(help_text='INSERT statements of the sample data, shown to students.'),
        ),
        migrations.RunPython(sql_topic_is_sql, migrations.RunPython.noop),
    ]
