# Generated by Django 5.2.17 on 2026-10-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0014_sql_check_data_tag_kind_ml64'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='about_md',
            field=models.TextField(blank=True),
        ),
    ]
