# Generated by Django 5.2.17 on 2026-10-04 20:09

import django.core.validators
from django.db import migrations, models

# Each problem starts at its level's rating (apps.problems.difficulty.LEVEL_RATING, copied so this
# keeps working if that changes); the recalc_difficulty sweep then re-rates it from its attempts.
LEVEL_RATING = {"beginner": 500, "easy": 700, "medium": 1000, "hard": 1300}


def start_at_level(apps, schema_editor):
    Problem = apps.get_model("problems", "Problem")
    for level, rating in LEVEL_RATING.items():
        Problem.objects.filter(difficulty=level).update(rating=rating)


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0015_tag_about_md'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='rating_guess',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(3500)]),
        ),
        migrations.RunPython(start_at_level, migrations.RunPython.noop),
    ]
