# Generated by Django 5.2.17 on 2026-10-08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0016_problem_rating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyproblem",
            name="selection_method",
            field=models.CharField(
                choices=[("auto", "Avtomatik"), ("admin", "Admin tanladi")],
                default="auto",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="dailyproblem",
            name="selected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="selected_daily_problems",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
